-- La gestión del esquema y datos iniciales se realiza mediante Flyway.
-- Este archivo se mantiene para compatibilidad con Docker (postgres docker-entrypoint-initdb.d).
-- Flyway aplicará las migraciones al iniciar la aplicación.
